PROJECT=lego_tools

GENERATED_EXECUTABLES=bin/build_mpd_file \
                      bin/fractal_landscape \
                      bin/pgm_to_ldraw \
                      bin/split_ldraw_file

GENERATED_SOURCES=mathematics-and-statistics old-command-line-packages

SCRIPTS=

